version: "3.9"

services:
  api:
    image: jacksonveroneze/templatewebapi-service:latest
    restart: always
    tty: true
    build:
      context: ../../src
      dockerfile: ./Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    healthcheck:
      test: curl --silent --fail http://api/health || exit 1
      interval: 15s
      timeout: 3s
      retries: 3
      start_period: 3s
    ports:
      - "8020-8025:80"
    networks:
      - public
      - internal
    links:
      - splunk
    logging:
      driver: "json-file"
      options:
        max-file: "2"
        max-size: "1m"