// <auto-generated />
using System;
using JacksonVeroneze.TemplateWebApi.Infrastructure.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace JacksonVeroneze.TemplateWebApi.Infrastructure.Migrations
{
    [ExcludeFromCodeCoverage]
    [DbContext(typeof(ApplicationDbContext))]
    partial class TemplateWebApiContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("JacksonVeroneze.TemplateWebApi.Domain.Entities.EmailEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_email");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_email_user_id");

                    b.ToTable("email", "public");
                });

            modelBuilder.Entity("JacksonVeroneze.TemplateWebApi.Domain.Entities.PhoneEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UserEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_entity_id");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_phone");

                    b.HasIndex("UserEntityId")
                        .HasDatabaseName("ix_phone_user_entity_id");

                    b.ToTable("phone", "public");
                });

            modelBuilder.Entity("JacksonVeroneze.TemplateWebApi.Domain.Entities.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("ActivedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actived_on_utc");

                    b.Property<DateOnly>("Birthday")
                        .HasColumnType("date")
                        .HasColumnName("birthday");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<int>("Gender")
                        .HasColumnType("integer")
                        .HasColumnName("gender");

                    b.Property<DateTime?>("InactivedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("inactived_on_utc");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_user");

                    b.ToTable("user", "public");
                });

            modelBuilder.Entity("JacksonVeroneze.TemplateWebApi.Domain.Entities.EmailEntity", b =>
                {
                    b.HasOne("JacksonVeroneze.TemplateWebApi.Domain.Entities.UserEntity", "User")
                        .WithMany("Emails")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_email_user_entity_user_temp_id");

                    b.OwnsOne("JacksonVeroneze.TemplateWebApi.Domain.ValueObjects.EmailValueObject", "Email", b1 =>
                        {
                            b1.Property<Guid>("EmailEntityId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("value");

                            b1.HasKey("EmailEntityId");

                            b1.ToTable("email", "public");

                            b1.WithOwner()
                                .HasForeignKey("EmailEntityId")
                                .HasConstraintName("fk_email_email_id");
                        });

                    b.Navigation("Email")
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("JacksonVeroneze.TemplateWebApi.Domain.Entities.PhoneEntity", b =>
                {
                    b.HasOne("JacksonVeroneze.TemplateWebApi.Domain.Entities.UserEntity", null)
                        .WithMany("Phones")
                        .HasForeignKey("UserEntityId")
                        .HasConstraintName("fk_phone_user_entity_user_entity_temp_id2");

                    b.OwnsOne("JacksonVeroneze.TemplateWebApi.Domain.ValueObjects.PhoneValueObject", "Phone", b1 =>
                        {
                            b1.Property<Guid>("PhoneEntityId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(11)
                                .HasColumnType("character varying(11)")
                                .HasColumnName("value");

                            b1.HasKey("PhoneEntityId");

                            b1.ToTable("phone", "public");

                            b1.WithOwner()
                                .HasForeignKey("PhoneEntityId")
                                .HasConstraintName("fk_phone_phone_id");
                        });

                    b.Navigation("Phone")
                        .IsRequired();
                });

            modelBuilder.Entity("JacksonVeroneze.TemplateWebApi.Domain.Entities.UserEntity", b =>
                {
                    b.OwnsOne("JacksonVeroneze.TemplateWebApi.Domain.ValueObjects.CpfValueObject", "Cpf", b1 =>
                        {
                            b1.Property<Guid>("UserEntityId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(11)
                                .HasColumnType("character varying(11)")
                                .HasColumnName("cpf");

                            b1.HasKey("UserEntityId");

                            b1.ToTable("user", "public");

                            b1.WithOwner()
                                .HasForeignKey("UserEntityId")
                                .HasConstraintName("fk_user_user_id");
                        });

                    b.OwnsOne("JacksonVeroneze.TemplateWebApi.Domain.ValueObjects.NameValueObject", "Name", b1 =>
                        {
                            b1.Property<Guid>("UserEntityId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("name");

                            b1.HasKey("UserEntityId");

                            b1.ToTable("user", "public");

                            b1.WithOwner()
                                .HasForeignKey("UserEntityId")
                                .HasConstraintName("fk_user_user_id");
                        });

                    b.Navigation("Cpf")
                        .IsRequired();

                    b.Navigation("Name")
                        .IsRequired();
                });

            modelBuilder.Entity("JacksonVeroneze.TemplateWebApi.Domain.Entities.UserEntity", b =>
                {
                    b.Navigation("Emails");

                    b.Navigation("Phones");
                });
#pragma warning restore 612, 618
        }
    }
}
