apiVersion: v1
kind: Namespace
metadata:
  name: templatewebapi-application
  
apiVersion: apps/v1
kind: Deployment
metadata:
  name: templatewebapi-deployment
  namespace: templatewebapi-application
  labels:
    app: templatewebapi-deployment
  annotations:
    prometheus.io/port: "8080"
    prometheus.io/scrape: "true"
    prometheus.io.scheme: "http"
    prometheus.io/path: "/metrics"
spec:
  replicas: 2
  strategy: 
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  selector:
    matchLabels:
      app: templatewebapi
  template:
    metadata:
      labels:
        app: templatewebapi
        version: "1.0"
    spec:
      containers:
        - name: templatewebapi
          image: jacksonveroneze/templatewebapi-service:0.0.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: 256Mi
              cpu: 100m
            requests:
              memory: 256Mi
              cpu: 100m
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          env:
            - name: APP_CONFIG_City__CacheExpMilisegundos
              valueFrom:
                configMapKeyRef:
                  name: templatewebapi-configmap
                  key: APP_CONFIG_City__CacheExpMilisegundos
            - name: APP_CONFIG_State__CacheExpMilisegundos
              valueFrom:
                configMapKeyRef:
                  name: templatewebapi-configmap
                  key: APP_CONFIG_State__CacheExpMilisegundos
            - name: APP_CONFIG_CacheType
              valueFrom:
                configMapKeyRef:
                  name: templatewebapi-configmap
                  key: APP_CONFIG_CacheType
            - name: APP_CONFIG_CacheEndpoint
              valueFrom:
                configMapKeyRef:
                  name: templatewebapi-configmap
                  key: APP_CONFIG_CacheEndpoint
            - name: APP_CONFIG_DistributedTracing__IsEnabled
              valueFrom:
                configMapKeyRef:
                  name: templatewebapi-configmap
                  key: APP_CONFIG_DistributedTracing__IsEnabled
            - name: APP_CONFIG_DistributedTracing__Jaeger__Host
              valueFrom:
                configMapKeyRef:
                  name: templatewebapi-configmap
                  key: APP_CONFIG_DistributedTracing__Jaeger__Host
            - name: APP_CONFIG_DistributedTracing__Jaeger__Port
              valueFrom:
                configMapKeyRef:
                  name: templatewebapi-configmap
                  key: APP_CONFIG_DistributedTracing__Jaeger__Port
            - name: Serilog__WriteTo__0__Args__configure__1__Name
              valueFrom:
                configMapKeyRef:
                  name: templatewebapi-configmap
                  key: Serilog__WriteTo__0__Args__configure__1__Name
            - name: Serilog__WriteTo__0__Args__configure__1__Args__serverUrl
              valueFrom:
                configMapKeyRef:
                  name: templatewebapi-configmap
                  key: Serilog__WriteTo__0__Args__configure__1__Args__serverUrl

---
apiVersion: v1
kind: Service
metadata:
  name: templatewebapi-service
  namespace: templatewebapi-application
spec:
  type: NodePort
  selector:
    app: templatewebapi
    version: "1.0"
  ports:
    - name: templatewebapi-service-port
      protocol: TCP
      port: 8084
      targetPort: 8080

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: api-horizontalpodautoscaler
  namespace: templatewebapi-application
spec:
  minReplicas: 2
  maxReplicas: 5
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: templatewebapi-deployment
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 5
    scaleUp:
      stabilizationWindowSeconds: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 70

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: stock-ingress
  namespace: templatewebapi-application
  annotations:
#    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
  labels:
    name: stock-ingress
spec:
  ingressClassName: public
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: templatewebapi-service
            port: 
              number: 8084