apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv-volume
  namespace: templatewebapi
  labels:
    type: local
    app: postgres
  annotations:
    pv.kubernetes.io/provisioned-by: dobs.csi.digitalocean.com
spec:
  storageClassName: do-block-storage
  persistentVolumeReclaimPolicy: Delete
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data/pg"

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-pv-claim
  namespace: templatewebapi
  labels:
    app: postgres
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1G
  storageClassName: do-block-storage

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  namespace: templatewebapi
  labels:
    app: postgres-catalog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-catalog
  template:
    metadata:
      labels:
        app: postgres-catalog
    spec:
      containers:
        - name: postgres
          image: postgres:13-alpine
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          env:
            - name: PGDATA
              valueFrom:
                configMapKeyRef:
                  name: templatewebapi-configmap
                  key: PGDATA

            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: templatewebapi-configmap
                  key: POSTGRES_DB

            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: templatewebapi-configmap
                  key: POSTGRES_USER

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: templatewebapi-secret
                  key: POSTGRES_PASSWORD
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgredb
      volumes:
        - name: postgredb
          persistentVolumeClaim:
            claimName: postgres-pv-claim

---

apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: templatewebapi
spec:
  type: NodePort
  selector:
    app: postgres-catalog
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432